#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/../lib";

use DDStartup::Manager;

my @args = @ARGV;
my $lines = 50;
if ( @args >= 2 && $args[0] eq '--lines' ) {
    $lines = $args[1];
    splice @args, 0, 2;
}

my $manager = DDStartup::Manager->new();
print $manager->logs( lines => $lines, argv => \@args );
