#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/../lib";

use DDStartup::Manager;

my $manager = DDStartup::Manager->new();
my ( $output, @args ) = $manager->parse_common_argv(@ARGV);
print $manager->render_result(
    output => $output,
    type   => 'record',
    result => $manager->remove(@args),
);
